# Generated by Django 5.0.2 on 2024-03-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Zara',
        ),
    ]
